# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Formato personalizado del prompt
format = '''
[┌───────────────────> $username](bold green) $time
[│ $localip ](bold green) $directory$rust$package
[└─>](bold green) '''

# Configuración de la hora
[time]
format = '[ $time](itallic yellow)'
use_12hr = true
disabled = false

[localip]
ssh_only = false
format = '@[$localipv4](bold red)'
disabled = false

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true
